# Generated by Django 2.2.5 on 2019-09-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20190909_1816'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='prof_favorito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='professor.Professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
