# Generated by Django 2.2.5 on 2019-09-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
